Add PAFS documentation
DEFRA/ruby-services-team pull request #93
Opened 2022-06-23 08:27 UTC by kennyevil

Adds documentation for the PAFS service

2022-06-23 08:38 UTC, timstone requested changes

2022-06-23 08:38 UTC, timstone commented on services/pafs/README.md
> +Pafs-user is the front office application for users to submit thheir project proposals
Typo

2022-06-23 08:38 UTC, timstone commented on services/pafs/README.md
> +`pafs-admin` and `pafs-user` have the ```main``` branch which uses the `main` branch from `pafs_core` and the `development` branch which uses the `develop` branch from `pafs_core`.
having a development branch and develop branch is confusing IMHO

2022-06-23 08:38 UTC, timstone commented on services/pafs/adding_new_areas.md
> +RMAs will have a subtype of either LA or WC.
Would be good to explain what LA and WC are

2022-06-23 08:38 UTC, timstone commented on services/pafs/adding_new_attributes_to_projects.md
> +The PAFS-user application sends data via a message that sends a JSON document to POL.
Explain POL accronym

2022-06-23 08:38 UTC, timstone commented on services/pafs/preparing_for_a_release.md
> +Post in the waste carriers channel on the Web Ops slack and say when you'd like to deploy.
waste carriers reference

2022-06-23 08:38 UTC, timstone commented on services/pafs/preparing_for_a_release.md
> +- Configuration item - "Waste Carriers, Dealers, Brokers".
Waste carriers reference

2023-03-24 14:24 UTC, jjromeo approved these changes
LGTM

2023-03-24 15:38 UTC, merged